# Publish all joint states -----------------------------------
door_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

door_position_controller:
  type: position_controllers/JointPositionController
  joint: door_joint
  pid: {p: 0.0, i: 0.0, d: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}

handle_position_controller:
  type: position_controllers/JointPositionController
  joint: handle_joint
  pid: {p: 2.0, i: 0.0, d: 0.0, i_clamp_min: 0.0, i_clamp_max: 0.0}
